fonts = [
    "8bitOperatorPlus-Bold.ttf",
    "8bitOperatorPlus-Regular.ttf",
    "8bitOperatorPlus8-Bold.ttf",
    "8bitOperatorPlus8-Regular.ttf",
    "8bitOperatorPlusSC-Bold.ttf",
    "8bitOperatorPlusSC-Regular.ttf",
    "ALBAM___.TTF",
    "ALBAS___.TTF",
    "ALBA____.TTF",
    "ALWAYSS.otf",
    "APSON.ttf",
    "ARTELA.ttf",
    "ARTLIF.otf",
    "AVISAH.otf",
    "AbrilFatface-Regular.ttf",
    "Achafexp.ttf",
    "Achafita.ttf",
    "Achaflft.ttf",
    "Achafont.ttf",
    "Achafout.ttf",
    "Achafsex.ttf",
    "Adventure Outline.ttf",
    "Adventure.ttf",
    "Aesthetic Midnight Slant.otf",
    "Aesthetic Midnight Slant.ttf",
    "Aesthetic Midnight.otf",
    "Aesthetic Midnight.ttf",
    "AlbertText-Bold.ttf",
    "AlbertTextBold.otf",
    "Aline.otf",
    "Aline.ttf",
    "Anarchy.ttf",
    "Antigua Coast.otf",
    "Antigua Coast.ttf",
    "Anton.ttf",
    "ArchitectsDaughter.ttf",
    "Arialic Hollow.ttf",
    "Arkitech Bold.ttf",
    "Arkitech Light.ttf",
    "Arkitech Medium.ttf",
    "Audiowide-Regular.ttf",
    "Austie Bost You Wear Flowers Hollow.ttf",
    "Austie Bost You Wear Flowers Solid.ttf",
    "AustieBostKittenKlub.ttf",
    "Avigea.ttf",
    "BLACKR~1.TTF",
    "BebasNeue-Regular.otf",
    "BebasNeue-Regular.ttf",
    "BingoReky.otf",
    "BingoReky.ttf",
    "Black Blood Ornament.otf",
    "Black Blood Ornament.ttf",
    "Black Blood.otf",
    "Black Blood.ttf",
    "Black Spider.otf",
    "Black Spider.ttf",
    "BlackOpsOne-Regular.ttf",
    "Blazed.ttf",
    "BodoniFLF-Bold.ttf",
    "BodoniFLF-BoldItalic.ttf",
    "BodoniFLF-Italic.ttf",
    "BodoniFLF-Roman.ttf",
    "BoogieNightsShadowNF.ttf",
    "BoyzRGrossShadowNF.ttf",
    "BrothersCircus-Regular.ttf",
    "BudmoJiggler.TTF",
    "Bullpen3D.ttf",
    "BullpenItalic.ttf",
    "CHLARA.otf",
    "CREAMPUF.TTF",
    "Canterbury.ttf",
    "Cartoon Blocks Christmas.ttf",
    "Channel.ttf",
    "Channel_Left-Slanted.ttf",
    "Channel_Slanted1.ttf",
    "Channel_Slanted2.ttf",
    "Chiki Bubbles.otf",
    "Chiki Bubbles.ttf",
    "Chiki.otf",
    "Chiki.ttf",
    "Claudette aime le Chocolat.ttf",
    "CutOutsFLF 2.ttf",
    "CutOutsFLF.ttf",
    "DENOLAX.ttf",
    "DEVASA.otf",
    "DHEYWI KANTHRI.ttf",
    "DS Bison Outline.otf",
    "DS Bison Outline.ttf",
    "Damned.ttf",
    "DancingScript-Bold.otf",
    "DancingScript-Bold.ttf",
    "DancingScript-Regular.otf",
    "DancingScript-Regular.ttf",
    "Daniel-Black.otf",
    "DayPosterShadowNF.ttf",
    "Doodie.otf",
    "Doodie.ttf",
    "Dunkin Bold Italic.ttf",
    "Dunkin Bold.ttf",
    "Dunkin Italic.ttf",
    "Dunkin Sans Bold Italic.ttf",
    "Dunkin Sans Bold.ttf",
    "Dunkin Sans Italic.ttf",
    "Dunkin Sans.ttf",
    "Dunkin.ttf",
    "ENDORALT.ttf",
    "ENDOR___.ttf",
    "ERHOS.otf",
    "Elinga.ttf",
    "Elizabella.otf",
    "Elizabella.ttf",
    "Emizen.otf",
    "Emizen.ttf",
    "Enjoy Christmas.otf",
    "Enjoy Christmas.ttf",
    "Etiquette.ttf",
    "Evafiya.ttf",
    "FontleroyBrownNF.ttf",
    "Fool For Love.ttf",
    "Four Signature.otf",
    "Four Signature.ttf",
    "FrakturShadowed.ttf",
    "FrederickatheGreat-Regular.ttf",
    "GANAMA.ttf",
    "Germania Shadow.ttf",
    "Gimbal Extended Regular.otf",
    "Gimbal Extended Regular.ttf",
    "Girls Have Many Secrets.ttf",
    "GistLight.otf",
    "Give It Your Heart.ttf",
    "Gramling Regular.otf",
    "Gramling Regular.ttf",
    "GramophoneShadedNF.ttf",
    "Gretoon.ttf",
    "GretoonHighlight.ttf",
    "HEROB.otf",
    "Hallies.otf",
    "Hallies.ttf",
    "Hamamih.ttf",
    "HomemadeApple.ttf",
    "IMMORTAL.ttf",
    "IMMRTLT_.ttf",
    "Interceptor Bold Italic.otf",
    "Interceptor Bold.otf",
    "Interceptor Italic.otf",
    "Interceptor.otf",
    "JIHASA ROSSCA.ttf",
    "JandaAppleCobbler.ttf",
    "JandaAppleCobblerSolid.ttf",
    "Jennifer Lynne Bold.ttf",
    "Jennifer Lynne.ttf",
    "Jhon Brewster.otf",
    "Jhon Brewster.ttf",
    "JosefinSans-Bold.ttf",
    "JosefinSans-BoldItalic.ttf",
    "JosefinSans-Italic.ttf",
    "JosefinSans-Light.ttf",
    "JosefinSans-LightItalic.ttf",
    "JosefinSans-Regular.ttf",
    "JosefinSans-SemiBold.ttf",
    "JosefinSans-SemiBoldItalic.ttf",
    "JosefinSans-Thin.ttf",
    "JosefinSans-ThinItalic.ttf",
    "KEAMLES.ttf",
    "KESHONEAN.otf",
    "KGALittleSwag.ttf",
    "KGSummerSunshine.ttf",
    "KGSummerSunshineBlackout.ttf",
    "KGSummerSunshineShadow.ttf",
    "KGTenThousandReasons.ttf",
    "KGTenThousandReasonsAlt.ttf",
    "KINKEE__.TTF",
    "KOMIKABB.ttf",
    "KOMIKABG.ttf",
    "KOMIKABS.ttf",
    "KOMIKAB_.ttf",
    "KOMIKAGL.ttf",
    "KOMIKAP_.ttf",
    "KOMIKATR.ttf",
    "KOMIKAX_.ttf",
    "KOMIKRAK.ttf",
    "KOMIKSKT.ttf",
    "Kabilah Robeda.ttf",
    "Kelly Stones.otf",
    "Kelly Stones.ttf",
    "KentuckyFriedChickenFont.ttf",
    "Kivaera.ttf",
    "LOKER.ttf",
    "Lemon-Regular.ttf",
    "LibreBaskerville-Bold.ttf",
    "LibreBaskerville-Italic.ttf",
    "LibreBaskerville-Regular.ttf",
    "LinkedNow-Extrabold.otf",
    "LinkedNow-ExtraboldItalic.otf",
    "LittleLordFontleroyNF.ttf",
    "Lobster 1.4.otf",
    "LuckiestGuy.ttf",
    "MEGHA.otf",
    "METALORD.TTF",
    "MITLHINA VICTORIAN.otf",
    "MONO PQU.otf",
    "Magnolia Light.ttf",
    "Magnolia.ttf",
    "Mahartha otf.otf",
    "Mahartha ttf.ttf",
    "Maksum.otf",
    "Maksum.ttf",
    "Marker Felt.ttf",
    "Marlboro.ttf",
    "Matchbook.ttf",
    "MeathFLF.ttf",
    "Merry Deer otf.otf",
    "Merry Deer ttf.ttf",
    "Mexcellent3D.ttf",
    "Miyabon.otf",
    "Miyabon.ttf",
    "Modern Serif Eroded.ttf",
    "Monoglyceride.ttf",
    "MonoglycerideBold.ttf",
    "MonoglycerideDemiBold.ttf",
    "MonoglycerideExtraBold.ttf",
    "MontereyFLF-Bold.ttf",
    "MontereyFLF-BoldItalic.ttf",
    "MontereyFLF-Italic.ttf",
    "MontereyFLF.ttf",
    "MontereyMediumFLF.ttf",
    "Montserrat-Bold.ttf",
    "Montserrat-Regular.ttf",
    "Mr Sunshine 2.ttf",
    "Mr Sunshine.ttf",
    "Natalie Beautyful.ttf",
    "News of the World italic.ttf",
    "News of the World regular.ttf",
    "News of the World wide italic.ttf",
    "News of the World wide.ttf",
    "Old English Five.ttf",
    "OldGateLaneNF.ttf",
    "Olde English Regular.ttf",
    "OpenSans-Bold.ttf",
    "OpenSans-BoldItalic.ttf",
    "OpenSans-ExtraBold.ttf",
    "OpenSans-ExtraBoldItalic.ttf",
    "OpenSans-Italic.ttf",
    "OpenSans-Light.ttf",
    "OpenSans-LightItalic.ttf",
    "OpenSans-Regular.ttf",
    "OpenSans-Semibold.ttf",
    "OpenSans-SemiboldItalic.ttf",
    "Optien.ttf",
    "PORKH___.TTF",
    "PORKYS_.TTF",
    "Pieces of Eight Alt.ttf",
    "Pieces of Eight.ttf",
    "Pinewood.ttf",
    "Prentiss.ttf",
    "Prisma.ttf",
    "QHOBERS.ttf",
    "QUASHA.otf",
    "RACQO.otf",
    "REFAGE.ttf",
    "ROBECK.otf",
    "RUTELUS.otf",
    "Ramonety.ttf",
    "Recollect.ttf",
    "Righteous-Regular.ttf",
    "Rochester-Regular.ttf",
    "Rocket City.ttf",
    "RockoFLF-Bold.ttf",
    "RockoFLF.ttf",
    "RockoUltraFLF-Bold.ttf",
    "RockoUltraFLF.ttf",
    "Ronald Hewitt.otf",
    "Ronald Hewitt.ttf",
    "Rothenburg Decorative.ttf",
    "SAPROTE PRO.otf",
    "SF Gushing Meadow SC.ttf",
    "SF Gushing Meadow.ttf",
    "Sandwich.otf",
    "Sandwich.ttf",
    "Sankutters.otf",
    "Sankutters.ttf",
    "Senopathi.ttf",
    "Sho-CardCapsNF.ttf",
    "Signarita Chloe.ttf",
    "Signarita Zhai Rhianne.ttf",
    "Simply Glamorous.ttf",
    "Sketch Gothic School.ttf",
    "Sketch Match.ttf",
    "SmallMemory.ttf",
    "Snowtop Caps.ttf",
    "Sofia-Regular.ttf",
    "StanleyMoon.otf",
    "StanleyMoon.ttf",
    "Straykid.ttf",
    "Stylebook.ttf",
    "Subway Black.ttf",
    "Subway Shadow.ttf",
    "Suissnord.otf",
    "SungAbed.otf",
    "SungAbed.ttf",
    "TYPEWR_B.TTF",
    "TYPEWR__.TTF",
    "Tabarra-Shadow-FFP.otf",
    "Tabarra-Shadow-Italic-FFP.otf",
    "Tell me a secret light.ttf",
    "Tell me a secret.ttf",
    "Terano Bold.otf",
    "Terano Bold.ttf",
    "Terano Regular.otf",
    "Terano Regular.ttf",
    "TheanoDidot-Regular.ttf",
    "Tobago Poster Alternate.ttf",
    "Tobago Poster Shadow.ttf",
    "Tobago Poster.ttf",
    "Transformers Movie.ttf",
    "VISHAR.otf",
    "Vellyc.ttf",
    "Virgo Display.otf",
    "Virgo Display.ttf",
    "Vonique 64 Bold Italic.ttf",
    "Vonique 64 Bold.ttf",
    "Vonique 64 Italic.ttf",
    "Vonique 64.ttf",
    "WAVAM.ttf",
    "Witch Pumpkin otf.otf",
    "Witch Pumpkin ttf.ttf",
    "Yahoo.ttf",
    "Yellow Rabbit.otf",
    "ZnikomitNo24.otf",
    "ZnikomitNo24Thin.otf",
    "a song for jennifer bold.ttf",
    "a song for jennifer.ttf",
    "airstrike.ttf",
    "airstrike3d.ttf",
    "airstrikeacad.ttf",
    "airstrikeb3d.ttf",
    "airstrikebold.ttf",
    "airstrikebullet.ttf",
    "airstrikechrome.ttf",
    "airstrikecond.ttf",
    "airstrikeexpand.ttf",
    "airstrikegrad.ttf",
    "airstrikehalf.ttf",
    "airstrikelaser.ttf",
    "airstrikeout.ttf",
    "airstrikeplat.ttf",
    "americangrain.otf",
    "americangrain.ttf",
    "americangrain3d.otf",
    "americangrain3d.ttf",
    "americangrain3dital.otf",
    "americangrain3dital.ttf",
    "americangrainacad.otf",
    "americangrainacad.ttf",
    "americangrainacadital.otf",
    "americangrainacadital.ttf",
    "americangrainbold.otf",
    "americangrainbold.ttf",
    "americangrainboldital.otf",
    "americangrainboldital.ttf",
    "americangrainboldout.otf",
    "americangrainboldout.ttf",
    "americangrainboldoutital.otf",
    "americangrainboldoutital.ttf",
    "americangrainchrome.otf",
    "americangrainchrome.ttf",
    "americangrainchromeital.otf",
    "americangrainchromeital.ttf",
    "americangraincond.otf",
    "americangraincond.ttf",
    "americangraincondital.otf",
    "americangraincondital.ttf",
    "americangrainexpand.otf",
    "americangrainexpand.ttf",
    "americangrainexpandital.otf",
    "americangrainexpandital.ttf",
    "americangraingrad.otf",
    "americangraingrad.ttf",
    "americangraingradital.otf",
    "americangraingradital.ttf",
    "americangrainhalf.otf",
    "americangrainhalf.ttf",
    "americangrainhalfital.otf",
    "americangrainhalfital.ttf",
    "americangrainital.otf",
    "americangrainital.ttf",
    "americangrainlaser.otf",
    "americangrainlaser.ttf",
    "americangrainlaserital.otf",
    "americangrainlaserital.ttf",
    "americangrainleft.otf",
    "americangrainleft.ttf",
    "americangrainout.otf",
    "americangrainout.ttf",
    "americangrainoutital.otf",
    "americangrainoutital.ttf",
    "americangrainsemital.otf",
    "americangrainsemital.ttf",
    "americangrainsuperital.otf",
    "americangrainsuperital.ttf",
    "armyrangers.ttf",
    "armyrangers3d.ttf",
    "armyrangers3dital.ttf",
    "armyrangersacad.ttf",
    "armyrangersacadital.ttf",
    "armyrangerschrome.ttf",
    "armyrangerschromeital.ttf",
    "armyrangerscond.ttf",
    "armyrangerscondital.ttf",
    "armyrangersengrav.ttf",
    "armyrangersengravital.ttf",
    "armyrangersexpand.ttf",
    "armyrangersexpandital.ttf",
    "armyrangersgrad.ttf",
    "armyrangersgradital.ttf",
    "armyrangershalf.ttf",
    "armyrangershalfital.ttf",
    "armyrangersital.ttf",
    "armyrangerslaser.ttf",
    "armyrangerslaserital.ttf",
    "armyrangersleft.ttf",
    "armyrangerssuperexpand.ttf",
    "armyrangerssuperexpandital.ttf",
    "bloodcrow.ttf",
    "bloodcrowc.ttf",
    "bloodcrowci.ttf",
    "bloodcrowe.ttf",
    "bloodcrowei.ttf",
    "bloodcrowi.ttf",
    "bloodcrowl.ttf",
    "bloodcrows.ttf",
    "bloodcrowsc.ttf",
    "bloodcrowsci.ttf",
    "bloodcrowsi.ttf",
    "cafeandbrewery.ttf",
    "code combination.otf",
    "coolvetica.ttf",
    "daniel.ttf",
    "danielbd.ttf",
    "docktrin.ttf",
    "ennobled.ttf",
    "federalescort.ttf",
    "federalescort3d.ttf",
    "federalescort3dital.ttf",
    "federalescortbullet.ttf",
    "federalescortbulletital.ttf",
    "federalescortchrome.ttf",
    "federalescortchromeital.ttf",
    "federalescortcond.ttf",
    "federalescortcondital.ttf",
    "federalescortexpand.ttf",
    "federalescortexpandital.ttf",
    "federalescorthalf.ttf",
    "federalescorthalfital.ttf",
    "federalescortital.ttf",
    "federalescortlaser.ttf",
    "federalescortlaserital.ttf",
    "federalescortleft.ttf",
    "federalescortout.ttf",
    "federalescortoutital.ttf",
    "federalescortscan.ttf",
    "federalescortscanital.ttf",
    "federalescortsemiital.ttf",
    "gisrida.ttf",
    "junegull.ttf",
    "mollita.otf",
    "mrsmonster.ttf",
    "mrsmonster3d.ttf",
    "mrsmonster3dital.ttf",
    "mrsmonsteracad.ttf",
    "mrsmonsterboldout.ttf",
    "mrsmonsterboldoutital.ttf",
    "mrsmonstercond.ttf",
    "mrsmonstercondital.ttf",
    "mrsmonsterexpand.ttf",
    "mrsmonsterexpandital.ttf",
    "mrsmonsterital.ttf",
    "mrsmonsterleft.ttf",
    "mrsmonsterout.ttf",
    "mrsmonsteroutital.ttf",
    "mrsmonsterrotal.ttf",
    "mrsmonsterrotate.ttf",
    "mrsmonsterrotate2.ttf",
    "neoncircuit.otf",
    "neoncircuit.ttf",
    "neoncircuit3d.otf",
    "neoncircuit3d.ttf",
    "neoncircuit3dital.otf",
    "neoncircuit3dital.ttf",
    "neoncircuitbold.otf",
    "neoncircuitbold.ttf",
    "neoncircuitboldital.otf",
    "neoncircuitboldital.ttf",
    "neoncircuitcond.otf",
    "neoncircuitcond.ttf",
    "neoncircuitcondital.otf",
    "neoncircuitcondital.ttf",
    "neoncircuitexpand.otf",
    "neoncircuitexpand.ttf",
    "neoncircuitexpandital.otf",
    "neoncircuitexpandital.ttf",
    "neoncircuitgrad.otf",
    "neoncircuitgrad.ttf",
    "neoncircuitgradital.otf",
    "neoncircuitgradital.ttf",
    "neoncircuitital.otf",
    "neoncircuitital.ttf",
    "neoncircuitleft.otf",
    "neoncircuitleft.ttf",
    "neoncircuitout.otf",
    "neoncircuitout.ttf",
    "neoncircuitoutital.otf",
    "neoncircuitoutital.ttf",
    "neoncircuitsemital.otf",
    "neoncircuitsemital.ttf",
    "neoncircuitsuperital.otf",
    "neoncircuitsuperital.ttf",
    "neoncircuittitle.otf",
    "neoncircuittitle.ttf",
    "neoncircuittitleital.otf",
    "neoncircuittitleital.ttf",
    "nokoko three.ttf",
    "orange juice 2.0.ttf",
    "pirulen.ttf",
    "planetbe.ttf",
    "raidercrusader.ttf",
    "raidercrusader3d.ttf",
    "raidercrusaderbevel.ttf",
    "raidercrusaderchrome.ttf",
    "raidercrusadercond.ttf",
    "raidercrusaderengrave.ttf",
    "raidercrusaderexpand.ttf",
    "raidercrusadergrad.ttf",
    "raidercrusaderhalf.ttf",
    "raidercrusaderital.ttf",
    "raidercrusaderlaser.ttf",
    "raidercrusaderleft.ttf",
    "raidercrusaderout.ttf",
    "raidercrusaderpunch.ttf",
    "raidercrusaderrotal.ttf",
    "raidercrusadersemistraight.ttf",
    "raidercrusadershiftdown.ttf",
    "raidercrusadershiftup.ttf",
    "raidercrusaderstraight.ttf",
    "raidercrusadertitle.ttf",
    "riesling.ttf",
    "shanghai.ttf",
    "skirmisher.ttf",
    "skirmisher3d.ttf",
    "skirmisher3dital.ttf",
    "skirmishercond.ttf",
    "skirmishercondital.ttf",
    "skirmisherexpand.ttf",
    "skirmisherexpandital.ttf",
    "skirmishergrad.ttf",
    "skirmishergradital.ttf",
    "skirmisherhalf.ttf",
    "skirmisherhalfital.ttf",
    "skirmisherital.ttf",
    "skirmisherlaser.ttf",
    "skirmisherlaserital.ttf",
    "skirmisherleft.ttf",
    "skirmisherrotal.ttf",
    "skirmishersemital.ttf",
    "staravenue.ttf",
    "theboldfont.ttf",
    "throwupz.ttf",
    "towerruins.ttf",
    "towerruins3d2.ttf",
    "towerruinsacad.ttf",
    "towerruinscond.ttf",
    "towerruinscondital.ttf",
    "towerruinsdrop.ttf",
    "towerruinsdropital.ttf",
    "towerruinsexpand.ttf",
    "towerruinsexpandital.ttf",
    "towerruinsital.ttf",
    "towerruinsleft.ttf",
    "towerruinsout.ttf",
    "towerruinsrotal.ttf",
    "towerruinsrotaleft.ttf",
    "towerruinsrotate.ttf",
    "towerruinsrotate2.ttf",
    "vtks chalk 79.ttf",
    "waltograph42.otf",
    "waltographUI.ttf",
    "xmasxpress.ttf",
    "xmasxpress3d.ttf",
    "xmasxpress3dital.ttf",
    "xmasxpressacad.ttf",
    "xmasxpressacadital.ttf",
    "xmasxpressital.ttf",
    "xmasxpressleft.ttf",
    "xmasxpressout.ttf",
    "xmasxpressoutital.ttf",
    "xmasxpressrotal.ttf",
    "xmasxpressrotate.ttf",
    "xmasxpressrotate2.ttf",
    "xmasxpressxpand.ttf",
    "xmasxpressxpandital.ttf"
    ]